[package]
name = "rust_scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
reqwest = {version ="0.12.22", features=["json"]}
scraper = "0.23.1"
tokio = {version ="1.46.1", features=["full"]}
